################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application/User/Core \
Application/User/Startup \
Application/User/TouchGFX/App \
Application/User/TouchGFX/Target \
Application/User/TouchGFX/Target/generated \
Application/User/generated \
Application/User/gui \
Drivers/BSP/Components \
Drivers/BSP/STM32U5x9J-DK \
Drivers/CMSIS \
Drivers/STM32U5xx_HAL_Driver \
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Non_Supported \
Middlewares/RTOS2/CMSIS/RTOS2/Heap/Heap_4 \
Middlewares/lvgl/env_support/rt-thread \
Middlewares/lvgl/env_support/rt-thread/squareline \
Middlewares/lvgl/src/core \
Middlewares/lvgl/src/draw/arm2d \
Middlewares/lvgl/src/draw \
Middlewares/lvgl/src/draw/nxp/pxp \
Middlewares/lvgl/src/draw/nxp/vglite \
Middlewares/lvgl/src/draw/sdl \
Middlewares/lvgl/src/draw/stm32_dma2d \
Middlewares/lvgl/src/draw/sw \
Middlewares/lvgl/src/draw/swm341_dma2d \
Middlewares/lvgl/src/extra/layouts/flex \
Middlewares/lvgl/src/extra/layouts/grid \
Middlewares/lvgl/src/extra/libs/bmp \
Middlewares/lvgl/src/extra/libs/ffmpeg \
Middlewares/lvgl/src/extra/libs/freetype \
Middlewares/lvgl/src/extra/libs/fsdrv \
Middlewares/lvgl/src/extra/libs/gif \
Middlewares/lvgl/src/extra/libs/png \
Middlewares/lvgl/src/extra/libs/qrcode \
Middlewares/lvgl/src/extra/libs/rlottie \
Middlewares/lvgl/src/extra/libs/sjpg \
Middlewares/lvgl/src/extra \
Middlewares/lvgl/src/extra/others/fragment \
Middlewares/lvgl/src/extra/others/gridnav \
Middlewares/lvgl/src/extra/others/ime \
Middlewares/lvgl/src/extra/others/imgfont \
Middlewares/lvgl/src/extra/others/monkey \
Middlewares/lvgl/src/extra/others/msg \
Middlewares/lvgl/src/extra/others/snapshot \
Middlewares/lvgl/src/extra/themes/basic \
Middlewares/lvgl/src/extra/themes/default \
Middlewares/lvgl/src/extra/themes/mono \
Middlewares/lvgl/src/extra/widgets/animimg \
Middlewares/lvgl/src/extra/widgets/calendar \
Middlewares/lvgl/src/extra/widgets/chart \
Middlewares/lvgl/src/extra/widgets/colorwheel \
Middlewares/lvgl/src/extra/widgets/imgbtn \
Middlewares/lvgl/src/extra/widgets/keyboard \
Middlewares/lvgl/src/extra/widgets/led \
Middlewares/lvgl/src/extra/widgets/list \
Middlewares/lvgl/src/extra/widgets/menu \
Middlewares/lvgl/src/extra/widgets/meter \
Middlewares/lvgl/src/extra/widgets/msgbox \
Middlewares/lvgl/src/extra/widgets/span \
Middlewares/lvgl/src/extra/widgets/spinbox \
Middlewares/lvgl/src/extra/widgets/spinner \
Middlewares/lvgl/src/extra/widgets/tabview \
Middlewares/lvgl/src/extra/widgets/tileview \
Middlewares/lvgl/src/extra/widgets/win \
Middlewares/lvgl/src/font \
Middlewares/lvgl/src/hal \
Middlewares/lvgl/src/misc \
Middlewares/lvgl/src/widgets \
Middlewares/ui/components \
Middlewares/ui/screens \
Middlewares/ui \

